### ISSUE TITLE
please help refining this template

### ISSUE THREAD

**Issue by LinguList** [lexibank/template#1]
This template repo exposes most of the basic possibilities, and could be used to start new datasets, or to check against when creating a new one. For me, that is easier than looking into the code or using pycharme, which I don't use anyway. I hope by exposing as much as one can, this will save a lot of time in the future.

**Comment by SimonGreenhill** [comment]
My opinionated suggestions in #2

**Comment by chrzyki** [comment]
Another question, not sure where this fits, so I'll just try this here: Are we going to go for a uniform 'presentation' in the respective CLDF ID columns? Particularly Parameter_ID, Form_ID, and Cognate_ID?

**Comment by SimonGreenhill** [comment]
yes please!

**Comment by SimonGreenhill** [comment]
I think this is done?
